spring.application.name=gitpilot
spring.security.oauth2.client.registration.github.client-id=Ov23liWw0vUOtHhfZiI8
spring.security.oauth2.client.registration.github.client-secret=faad11ad1bbaba19e84cbeb69dc6ef2df18a1915
spring.datasource.url=jdbc:postgresql://localhost:5432/gitpilot
spring.datasource.username=postgres
spring.datasource.password=venky2005
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
management.endpoints.web.exposure.include=health,info

